# @package _global_
exp_name: ${masking.name}
seed: 0
model: resnet50
ckpt_interval: 50

wandb:
  project: cifar 100
  name: ${dataset.name}_${exp_name}_density_${masking.density}

masking:
  dense: True
  density: 1

dataset:
  batch_size: 128
  validation_split: 0.1

optimizer:
  epochs: 250
  lr: 0.1
  momentum: 0.9
  weight_decay: 5e-4
  label_smoothing: 0.1
  decay_frequency: 30000
  warmup_steps: 2112
  decay_factor: 0.2
